name: Output information
on: workflow_dispatch
jobs: 
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context without JSON
        run: echo "${{ github }}"
      - name: Output GitHub context with JSON
        run: echo "${{ toJSON(github) }}"